# Brief: the monitoring rate, monitor_time = 1.0 / monitor_rate_
# example: monitor_rate_=2hz, monitor_time=0.5s, monitor_rate_=0.1hz, monitor_time=10s
monitor_rate: 1.0

# Brief: ros topics for each vehicles
name_space: alpha_img

srv_get_state: helm/get_state

srv_get_states: helm/get_states

srv_change_state: helm/change_state

# Brief: the abort action
abort_action:
    # brief: 
    #  state: state name that monitored
    #  timeout: max time stey in this state, e.g., 2h=7200s
    #  transition: MVP will transit to this state if timeout

  # - state: kill
  #   timeout: 1.0  
  #   transition: start

  - state: start
    timeout: .inf  
    transition: kill

  - state: survey_3d
    timeout: 5.0
    transition: start

  - state: direct_control
    timeout: 5.0
    transition: start

# Brief: another action